CC=gcc
CFLAGS=-g -std=c99 -Wall
LDFLAGS=-lm

test2a:
	./part2a #no parameters
	./part2a "only_one_parameter"
	./part2a "biggest_parameter" "at" "start"
	./part2a "biggest" "parameter" "at" "the" "end" "very_very_very_big_parameter"
	./part2a "answer" "somewhere" "in" "the" "middle"
	./part2a "two" "strings" "the" "same" "length" "ha_ha_!"
